import type { Metadata } from "next";
import "@/styles/globals.css";
import { Inter as FontSans } from "next/font/google"

import { cn } from "@/lib/utils"
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { CartContextProvider } from '@/hooks/useCart';
import AuthProvider from '@/hooks/SessionProvider';
import { authOptions } from '../api/auth/[...nextauth]/options';

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Agrivest Africa",
	description: "Generated by create next app",
	icons: "/images/logo.png",
	keywords: ["agriculture", "africa", "ghana", "farming", "crowdfund"]
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<AuthProvider>
			<html lang="en" suppressHydrationWarning>
				<body className={cn(
					"min-h-screen bg-background font-sans antialiased",
					fontSans.variable
				)}>
					<nav>
						<Header />
					</nav>
					<CartContextProvider>

						{children}

					</CartContextProvider>

					<footer>
						<Footer />
					</footer>
				</body>
			</html>
		</AuthProvider>

	);
}
